build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests:
      environment:
        timezone: FR
        php:
          version: 7.4

      services:
        mysql: 5.7

      dependencies:
        override:
          - wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz --no-check-certificate
          - tar -xvf sqlite-autoconf-3380500.tar.gz && cd sqlite-autoconf-3380500
          - ./configure
          - make
          - sudo make install
          - export PATH="/usr/local/lib:$PATH"
          - cd ..

      tests:
        override:
          - command: XDEBUG_MODE=coverage composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
