build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests:
      environment:
        timezone: FR
        php:
          version: 7.4

      services:
        mysql: 5.7

      tests:
        override:
          - command: XDEBUG_MODE=coverage composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
