dist: bionic
language: php

services: mysql

php:
  - 7.4
  - 8.0

jobs:
  include:
    - stage: analysis
      php: 7.4
      script:
        - composer psalm

install:
  - travis_retry composer install

script:
  - composer tests
