name: Coding Style

on:
  push:
    branches: [ '[1-9].[0-9]+' ]
  pull_request:
    branches: [ '[1-9].[0-9]+' ]

jobs:
  run:
    runs-on: ubuntu-latest
    name: PHP 8.0
    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.0"
        extensions: json
        ini-values: post_max_size=256M
        coverage: xdebug        
        tools: php-cs-fixer, phpunit

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check code style issues
      run: composer run-script php-cs-fixer
